(() => {
  'use strict';
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = s => document.querySelector(s);
  const W = 32, H = 22;
  const STAT = {
    force:{label:'STRENGTH',glyph:'◆',color:'#d96658'}, agilite:{label:'AGILITY',glyph:'»',color:'#72a7b5'},
    magie:{label:'MAGIC',glyph:'✦',color:'#ad86c8'}, intelligence:{label:'INTELLECT',glyph:'⌘',color:'#d9b463'}
  };
  const PREFIX = ['Shattered','Ravenous','Astral','Silent','Runic','Bloodforged','Spectral','Ancient'];
  const NAMES = {force:['Axe','Warhammer','Greatsword'],agilite:['Dagger','Rapier','Bow'],magie:['Staff','Orb','Scepter'],intelligence:['Grimoire','Catalyst','Relic']};
  const GLYPHS={force:'⚒',agilite:'†',magie:'ϟ',intelligence:'⌬'};
  const RELICS={force:['Colossus Ring','Ogre Fang'],agilite:['Raven Feather','Thief Boots'],magie:['Arcane Shard','Star Larva'],intelligence:['Sage Eye','Memory Rune']};
  const STORAGE_NAME='roguotoo.playerName', STORAGE_SCORES='roguotoo.scores', STORAGE_CONTROLS='roguotoo.controls', STORAGE_THEME='roguotoo.theme';
  const THEMES=['studio','flash','classic'];
  let activeTheme=THEMES.includes(localStorage.getItem(STORAGE_THEME))?localStorage.getItem(STORAGE_THEME):'studio';
  const themeButton=$('#theme-button'),themeMenu=$('#theme-menu');
  function setTheme(theme,persist=true){activeTheme=THEMES.includes(theme)?theme:'studio';document.documentElement.dataset.theme=activeTheme;if(persist)localStorage.setItem(STORAGE_THEME,activeTheme);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',getComputedStyle(document.documentElement).getPropertyValue('--bg').trim());document.querySelectorAll('[data-theme-choice]').forEach(button=>button.setAttribute('aria-checked',String(button.dataset.themeChoice===activeTheme)));}
  function toggleThemeMenu(open=!themeMenu.hidden){themeMenu.hidden=!open;themeButton.setAttribute('aria-expanded',String(open));if(open)themeMenu.querySelector('[aria-checked="true"]')?.focus()}
  themeButton.onclick=e=>{e.stopPropagation();toggleThemeMenu(themeMenu.hidden)};
  document.querySelectorAll('[data-theme-choice]').forEach(button=>button.onclick=()=>{setTheme(button.dataset.themeChoice);toggleThemeMenu(false);themeButton.focus()});
  document.addEventListener('click',e=>{if(!e.target.closest('.theme-control'))toggleThemeMenu(false)});
  themeMenu.addEventListener('keydown',e=>{const items=[...themeMenu.querySelectorAll('[data-theme-choice]')],index=items.indexOf(document.activeElement);if(e.key==='Escape'){toggleThemeMenu(false);themeButton.focus()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();items[(index+(e.key==='ArrowDown'?1:-1)+items.length)%items.length].focus()}});
  setTheme(activeTheme,false);
  document.querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>move(...button.dataset.move.split(',').map(Number)));
  document.querySelectorAll('[data-wait]').forEach(button=>button.onclick=waitTurn);
  $('[data-touch-restart]').onclick=restartGame;
  if(localStorage.getItem(STORAGE_NAME)==='SANS-NOM')localStorage.setItem(STORAGE_NAME,'NAMELESS');
  let controlMode=localStorage.getItem(STORAGE_CONTROLS)||'azerty';
  let state, tileW, tileH, ox, oy, raf, slotSession=null, audio=true;
  const sound=(()=>{let ac,master,reverb,ambientTimer,enabled=true;const now=()=>ac.currentTime;
    function init(){if(ac)return;ac=new(window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.42;master.connect(ac.destination);reverb=ac.createConvolver();const len=ac.sampleRate*1.15,imp=ac.createBuffer(2,len,ac.sampleRate);for(let c=0;c<2;c++){const d=imp.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.8)}reverb.buffer=imp;const wet=ac.createGain();wet.gain.value=.16;reverb.connect(wet);wet.connect(master)}
    function resume(){init();if(ac.state==='suspended')ac.resume()}
    function route(node,wet=.12){node.connect(master);if(wet){const g=ac.createGain();g.gain.value=wet;node.connect(g);g.connect(reverb)}}
    function osc(freq,dur=.08,type='sine',vol=.035,endFreq=freq,wet=.08,delay=0){if(!enabled)return;resume();const t=now()+delay,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);route(g,wet);o.start(t);o.stop(t+dur+.02)}
    function noise(dur=.08,vol=.025,filterFreq=500,wet=.1,delay=0){if(!enabled)return;resume();const t=now()+delay,b=ac.createBuffer(1,Math.ceil(ac.sampleRate*dur),ac.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const src=ac.createBufferSource(),f=ac.createBiquadFilter(),g=ac.createGain();src.buffer=b;f.type='lowpass';f.frequency.value=filterFreq;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);src.connect(f);f.connect(g);route(g,wet);src.start(t)}
    function footstep(){noise(.055,.022,rng(650,950),.2);osc(rng(70,90),.045,'sine',.018,45,.12)}
    function attack(){noise(.09,.035,1800,.12);osc(260,.1,'sawtooth',.025,90,.08)}
    function impact(){noise(.075,.045,700,.17);osc(85,.12,'square',.022,42,.12)}
    function pickup(){osc(440,.08,'sine',.025,620,.16);osc(660,.11,'sine',.018,880,.2,.07)}
    function casinoTick(){osc(rng(720,1100),.025,'square',.012,rng(480,680),.04);noise(.018,.008,2400,.03)}
    function jackpot(){[523,659,784,1047].forEach((f,i)=>osc(f,.16,'triangle',.032,f*1.03,.24,i*.085));osc(131,.48,'sine',.025,196,.3,.02);noise(.12,.016,3200,.2,.27)}
    function alert(){osc(105,.28,'sine',.018,82,.32);osc(210,.16,'triangle',.009,170,.3,.08)}
    function rumble(){noise(1.25,.025,130,.28);osc(52,1.35,'sawtooth',.018,31,.35);osc(38,.9,'sine',.025,25,.25,.22)}
    function breathe(){if(!enabled)return;resume();const duration=2.8+Math.random()*2.4,o=ac.createOscillator(),f=ac.createBiquadFilter(),g=ac.createGain(),t=now();o.type='sine';o.frequency.value=34+Math.random()*9;f.type='lowpass';f.frequency.value=90;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(.008,t+duration*.48);g.gain.linearRampToValueAtTime(.0001,t+duration);o.connect(f);f.connect(g);route(g,.38);o.start(t);o.stop(t+duration)}
    function scheduleAmbient(){clearTimeout(ambientTimer);ambientTimer=setTimeout(()=>{if(Math.random()>.32)breathe();scheduleAmbient()},rng(4500,10500))}
    function start(){resume();scheduleAmbient()}
    function setEnabled(value){enabled=value;resume();master.gain.setTargetAtTime(value?.42:0,now(),.04);if(value)scheduleAmbient();else clearTimeout(ambientTimer)}
    return{start,setEnabled,footstep,attack,impact,pickup,casinoTick,jackpot,alert,rumble,beep:osc};})();
  const rng=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[rng(0,a.length-1)];

  function freshState(){return {running:false,room:1,type:'exploration',map:[],player:{name:localStorage.getItem(STORAGE_NAME)||'NAMELESS',x:2,y:2,hp:30,maxHp:30,level:1,xp:0,nextXp:20,gold:0,points:3,stats:{force:1,agilite:1,magie:1,intelligence:1},weapon:makeWeapon(1)},inventory:[],relics:[],enemies:[],potions:[],chests:[],exit:null,inCombat:false,logs:[],turn:0};}
  function makeWeapon(level=1){const stat=pick(Object.keys(STAT)), base=rng(3,6)+level;return {id:crypto.randomUUID(),name:`${pick(PREFIX)} ${pick(NAMES[stat])}`,stat,damage:base,bonus:rng(1,Math.max(1,Math.ceil(level/2))),price:base*4+rng(3,12),glyph:GLYPHS[stat]};}
  function carveRoom(map,x,y,w,h){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)map[yy][xx]='.';}
  function generateRoom(){
    state.map=Array.from({length:H},()=>Array(W).fill('#')); const rooms=[];
    const count=rng(4,7);
    for(let i=0;i<count;i++){let w=rng(5,10),h=rng(4,7),x=rng(1,W-w-2),y=rng(1,H-h-2);carveRoom(state.map,x,y,w,h);const c={x:Math.floor(x+w/2),y:Math.floor(y+h/2)};rooms.push(c);if(i){let p=rooms[i-1],cx=p.x,cy=p.y;while(cx!==c.x){state.map[cy][cx]='.';cx+=Math.sign(c.x-cx)}while(cy!==c.y){state.map[cy][cx]='.';cy+=Math.sign(c.y-cy)}state.map[cy][cx]='.'}}
    state.player.x=rooms[0].x;state.player.y=rooms[0].y;state.exit={...rooms.at(-1)};state.enemies=[];state.potions=[];state.chests=[];
    const n=Math.min(8,2+Math.floor(state.room*.65));for(let i=0;i<n;i++){const r=rooms[rng(1,rooms.length-1)];let x=r.x+rng(-2,2),y=r.y+rng(-1,1);if(openAt(x,y)&&!(x===state.exit.x&&y===state.exit.y))state.enemies.push(makeEnemy(x,y));}
    state.type=state.room%5===0?'boutique':'exploration';state.inCombat=false;if(state.running)sound.rumble();addLog(state.type==='boutique'?'The scent of gold drifts near the exit.':'The room reshapes itself around you.','good'); updateUI();
  }
  function makeEnemy(x,y){const kinds=[['rat','r',5,2],['goblin','g',8,3],['wraith','s',11,4],['ogre','O',17,6]],k=kinds[Math.min(kinds.length-1,Math.floor((state.room+rng(0,4))/5))];return {x,y,name:k[0],glyph:k[1],hp:k[2]+state.room,maxHp:k[2]+state.room,damage:k[3]+Math.floor(state.room/6)};}
  function openAt(x,y){return x>0&&y>0&&x<W&&y<H&&state.map[y]?.[x]==='.';}
  function move(dx,dy){if(!state.running||$('.modal').classList.contains('visible'))return;const p=state.player,nx=p.x+dx,ny=p.y+dy;if(!openAt(nx,ny))return tone(90,.03);const enemy=state.enemies.find(e=>e.x===nx&&e.y===ny);if(enemy){attack(enemy);}else{p.x=nx;p.y=ny;sound.footstep();drinkPotionAt(nx,ny);const opened=openChestAt(nx,ny);enemyTurn();if(!opened&&nx===state.exit.x&&ny===state.exit.y&&state.enemies.length===0)completeRoom();}updateCombat();updateUI();}
  function waitTurn(){if(!state.running||$('.modal').classList.contains('visible'))return;enemyTurn();updateCombat();updateUI();}
  function restartGame(){if(state.running&&confirm('Restart this chronicle?'))startGame();}
  function attack(e){const p=state.player,w=p.weapon,s=p.stats[w.stat];let dmg=w.damage+Math.floor(s*1.45)+rng(0,2);if(w.stat==='agilite'&&Math.random()<s*.025)dmg*=2;if(w.stat==='magie')dmg+=Math.floor(p.stats.intelligence*.45);sound.attack();e.hp-=dmg;floatText(e.x,e.y,`-${dmg}`,STAT[w.stat].color);sound.impact();addLog(`${w.name} deals ${dmg} damage to the ${e.name}.`);if(e.hp<=0){state.enemies=state.enemies.filter(x=>x!==e);const gold=rng(2,6)+Math.floor(state.room/2),xp=rng(5,9);p.gold+=gold;gainXp(xp);addLog(`${e.name} slain · +${gold} gold · +${xp} XP`,'good');const drop=rng(1,100);if(drop<=25){state.chests.push({x:e.x,y:e.y});addLog('A mysterious chest drops to the ground!','good')}else if(drop<=39){state.potions.push({x:e.x,y:e.y,heal:rng(7,11)+p.level});addLog(`The ${e.name} drops a health potion!`,'good')}tone(320,.08)}enemyTurn();}
  function drinkPotionAt(x,y){const i=state.potions.findIndex(p=>p.x===x&&p.y===y);if(i<0)return;const potion=state.potions[i],before=state.player.hp;state.player.hp=Math.min(state.player.maxHp,state.player.hp+potion.heal);state.potions.splice(i,1);const healed=state.player.hp-before;floatText(x,y,`+${healed}`,'#ed3f65');addLog(healed?`Health potion consumed · +${healed} HP.`:'Potion consumed, but your health is already full.','good');sound.pickup();}
  function rollChestReward(){const roll=rng(1,100);if(roll<=48)return{type:'gold',amount:rng(8,18)+state.room*2};if(roll<=70)return{type:'heal',amount:rng(4,8)+Math.floor(state.player.level/2)};const stat=pick(Object.keys(STAT));return{type:'stat',stat,name:pick(RELICS[stat])};}
  function openChestAt(x,y){const i=state.chests.findIndex(c=>c.x===x&&c.y===y);if(i<0)return false;state.chests.splice(i,1);const count=Math.random()<.18?3:Math.random()<.5?2:1,rewards=Array.from({length:count},rollChestReward);$('#modal').innerHTML=`<div class="dialog chest-dialog slot-dialog"><span class="eyebrow">RARE LOOT</span><h2>MYSTERIOUS CHEST</h2><div class="chest-rewards">${rewards.map(()=>`<div class="chest-reward spinning" style="--reward:#d9b463"><span class="slot-symbol">?</span><strong>???</strong><small>REWARD</small></div>`).join('')}</div><button class="primary slot-stop" data-stop>[ SPACE ] STOP</button></div>`;$('#modal').classList.add('visible');const symbols=['●','♥','◆','»','✦','⌘','?'];slotSession={rewards,timer:setInterval(()=>{document.querySelectorAll('.slot-symbol').forEach(el=>{el.textContent=pick(symbols);el.style.color=pick(['#d9b463','#ed3f65','#72a7b5','#ad86c8','#a8d46f']);el.parentElement.style.transform=`translateY(${rng(-3,3)}px)`});sound.casinoTick()},70)};$('[data-stop]').onclick=finalizeChest;sound.pickup();return true;}
  function finalizeChest(){if(!slotSession)return;clearInterval(slotSession.timer);const shown=slotSession.rewards.map(r=>{if(r.type==='gold'){state.player.gold+=r.amount;return{glyph:'●',name:`${r.amount} GOLD`,detail:'Fortune smiles upon you.',color:'#d9b463'}}if(r.type==='heal'){const before=state.player.hp;state.player.hp=Math.min(state.player.maxHp,state.player.hp+r.amount);return{glyph:'♥',name:'MINI POTION',detail:`+${state.player.hp-before} HP`,color:'#ed3f65'}}state.player.stats[r.stat]++;if(r.stat==='force'){state.player.maxHp+=2;state.player.hp+=2}state.relics.push({name:r.name,stat:r.stat});return{glyph:STAT[r.stat].glyph,name:r.name,detail:`+1 ${STAT[r.stat].label}`,color:STAT[r.stat].color}});slotSession=null;addLog(`Chest opened · ${shown.map(r=>r.name).join(', ')}.`,'good');sound.jackpot();$('#modal').innerHTML=`<div class="dialog chest-dialog"><span class="eyebrow">JACKPOT</span><h2>LOOT REVEALED</h2><div class="chest-rewards">${shown.map(r=>`<div class="chest-reward" style="--reward:${r.color}"><span>${r.glyph}</span><strong>${r.name}</strong><small>${r.detail}</small></div>`).join('')}</div><button class="primary" data-close>[ COLLECT ]</button></div>`;$('[data-close]').onclick=()=>{$('#modal').classList.remove('visible');updateUI()};updateUI();}
  function enemyTurn(){const p=state.player;state.turn++;for(const e of state.enemies){let dist=Math.abs(e.x-p.x)+Math.abs(e.y-p.y);if(dist===1){const dodge=Math.min(.35,p.stats.agilite*.025);if(Math.random()>dodge){const d=Math.max(1,e.damage-rng(0,2));p.hp-=d;floatText(p.x,p.y,`-${d}`,'#d96658');addLog(`${e.name} hits you for ${d}.`,'bad');tone(70,.07)}}else if(dist<8){const dx=Math.sign(p.x-e.x),dy=Math.sign(p.y-e.y);const opts=Math.random()<.5?[[dx,0],[0,dy]]:[[0,dy],[dx,0]];for(const [mx,my] of opts){const nx=e.x+mx,ny=e.y+my;if(openAt(nx,ny)&&!occupied(nx,ny)){e.x=nx;e.y=ny;break}}}}if(p.hp<=0)gameOver();}
  function occupied(x,y){return (state.player.x===x&&state.player.y===y)||state.enemies.some(e=>e.x===x&&e.y===y);}
  function updateCombat(){const wasInCombat=state.inCombat;state.inCombat=state.enemies.some(e=>Math.abs(e.x-state.player.x)+Math.abs(e.y-state.player.y)<7);if(!wasInCombat&&state.inCombat)sound.alert();}
  function gainXp(n){const p=state.player;p.xp+=n;while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.45);p.points+=2;p.maxHp+=5;p.hp=p.maxHp;addLog(`LEVEL ${p.level} · 2 attribute points gained.`,'good');}}
  function completeRoom(){if(state.type==='boutique')openShop();else{state.room++;generateRoom();}}
  function openShop(){
    let weapons=Array.from({length:4},()=>makeWeapon(state.player.level+Math.floor(state.room/5)));
    let artifacts=Array.from({length:3},()=>{const stat=pick(Object.keys(STAT));return{id:crypto.randomUUID(),stat,name:pick(RELICS[stat]),glyph:STAT[stat].glyph,price:18+state.room*3+rng(0,12)}});
    const leave=()=>{state.room++;$('#modal').classList.remove('visible');generateRoom()};
    const notify=(text,type='buy')=>{const toast=document.createElement('div');toast.className=`shop-toast ${type}`;toast.textContent=text;$('.shop-dialog')?.append(toast);setTimeout(()=>toast.remove(),1250)};
    function render(){const p=state.player,inventoryFull=state.inventory.length>=4;
      const weaponRows=weapons.map(w=>`<button class="shop-row" data-buy-weapon="${w.id}" ${p.gold<w.price||inventoryFull?'disabled':''} style="--item-color:${STAT[w.stat].color}"><span class="shop-glyph">${w.glyph}</span><span><b>${w.name}</b><small>${w.damage} DMG · ${STAT[w.stat].label} +${w.bonus}</small></span><em>${inventoryFull?'FULL':`${w.price} G`}</em></button>`).join('');
      const artifactRows=artifacts.map(a=>`<button class="shop-row" data-buy-artifact="${a.id}" ${p.gold<a.price?'disabled':''} style="--item-color:${STAT[a.stat].color}"><span class="shop-glyph">${a.glyph}</span><span><b>${a.name}</b><small>PERMANENT +1 ${STAT[a.stat].label}${a.stat==='force'?' · +2 HP':''}</small></span><em>${a.price} G</em></button>`).join('');
      const sellRows=state.inventory.map(w=>{const value=Math.max(1,Math.floor(w.price*.45));return`<button class="shop-row sell-row" data-sell="${w.id}" style="--item-color:${STAT[w.stat].color}"><span class="shop-glyph">${w.glyph}</span><span><b>${w.name}</b><small>${w.damage} DMG · SELL ITEM</small></span><em>+${value} G</em></button>`}).join('');
      $('#modal').innerHTML=`<div class="dialog shop-dialog"><header class="shop-header"><span><small>WANDERING MERCHANT // ROOM ${String(state.room).padStart(2,'0')}</small><b>THE EMPORIUM</b></span><strong><i>●</i> ${p.gold} GOLD</strong><button class="shop-close" data-leave aria-label="Leave shop">×</button></header><div class="shop-layout"><div class="shop-catalog"><section><h3>WEAPONS <small>${weapons.length} IN STOCK</small></h3><div class="shop-list">${weaponRows||'<p class="shop-empty">SOLD OUT</p>'}</div></section><section><h3>ARTIFACTS <small>PERMANENT UPGRADES</small></h3><div class="shop-list">${artifactRows||'<p class="shop-empty">SOLD OUT</p>'}</div></section></div><aside class="shop-sell"><h3>SELL <small>YOUR INVENTORY</small></h3><p>Select an item to sell it to the merchant.</p><div class="shop-list">${sellRows||'<p class="shop-empty">YOUR INVENTORY IS EMPTY</p>'}</div><div class="merchant-note"><span>$</span><p>“Gold is useless<br>to the dead.”</p></div></aside></div><div class="shop-footer"><span>${inventoryFull?'INVENTORY FULL · SELL AN ITEM TO MAKE ROOM':'CLICK OR TAP AN ITEM TO TRADE'}</span><button class="primary" data-leave>[ LEAVE SHOP ]</button></div></div>`;
      $('#modal').classList.add('visible');document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=leave);
      weapons.forEach(w=>$(`[data-buy-weapon="${w.id}"]`)?.addEventListener('click',()=>{if(p.gold<w.price||state.inventory.length>=4)return;p.gold-=w.price;state.inventory.push(w);weapons=weapons.filter(item=>item.id!==w.id);addLog(`${w.name} purchased for ${w.price} gold.`,'good');sound.pickup();updateUI();render();notify(`PURCHASED // ${w.name}`)}));
      artifacts.forEach(a=>$(`[data-buy-artifact="${a.id}"]`)?.addEventListener('click',()=>{if(p.gold<a.price)return;p.gold-=a.price;p.stats[a.stat]++;if(a.stat==='force'){p.maxHp+=2;p.hp+=2}state.relics.push({name:a.name,stat:a.stat});artifacts=artifacts.filter(item=>item.id!==a.id);addLog(`${a.name} purchased · +1 ${STAT[a.stat].label}.`,'good');sound.pickup();updateUI();render();notify(`ARTIFACT ACQUIRED // +1 ${STAT[a.stat].label}`)}));
      state.inventory.forEach(w=>$(`[data-sell="${w.id}"]`)?.addEventListener('click',()=>{const value=Math.max(1,Math.floor(w.price*.45));p.gold+=value;state.inventory=state.inventory.filter(item=>item.id!==w.id);addLog(`${w.name} sold for ${value} gold.`,'good');tone(520,.06);updateUI();render();notify(`SOLD // +${value} GOLD`,'sell')}));
    }
    render();
  }
  function getScores(){try{return JSON.parse(localStorage.getItem(STORAGE_SCORES))||[]}catch{return []}}
  function saveScore(){const p=state.player,scores=getScores();scores.push({name:p.name||'NAMELESS',room:state.room,level:p.level,gold:p.gold,score:state.room*100+p.level*25+p.gold,date:Date.now()});scores.sort((a,b)=>b.score-a.score);localStorage.setItem(STORAGE_SCORES,JSON.stringify(scores.slice(0,10)));}
  function showScores(){const scores=getScores(),ended=!state.running&&state.player.hp<=0,rows=scores.map((s,i)=>`<div class="score-row"><span>${i+1}.</span><strong>${escapeHtml(s.name)}</strong><span>ROOM ${s.room}</span><span>LVL. ${s.level}</span><span>${s.score} PTS</span></div>`).join('');$('#modal').innerHTML=`<div class="dialog"><span class="eyebrow">VOID ARCHIVES</span><h2>HIGH SCORES</h2><div class="score-list"><div class="score-row header"><span>#</span><span>NAME</span><span>ROOM</span><span>LEVEL</span><span>SCORE</span></div>${rows||'<div class="score-empty">No chronicles recorded yet.</div>'}</div>${ended?'<button class="primary" data-restart>[ START A NEW RUN ]</button>':'<button class="primary" data-close>[ CLOSE ]</button>'}</div>`;$('#modal').classList.add('visible');if(ended)$('[data-restart]').onclick=startGame;else $('[data-close]').onclick=()=>$('#modal').classList.remove('visible');}
  function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function gameOver(){state.running=false;saveScore();$('#modal').innerHTML=`<div class="dialog"><span class="eyebrow">CHRONICLE ENDED</span><h2>YOU DIED</h2><p>${state.room} rooms cleared · level ${state.player.level}<br>${state.player.gold} gold collected</p><button class="primary" data-restart>[ START A NEW RUN ]</button><button class="tiny-button" data-scores>[ VIEW SCORES ]</button></div>`;$('#modal').classList.add('visible');$('[data-scores]').onclick=showScores;$('[data-restart]').onclick=startGame;}
  function addStat(k){if(state.inCombat||state.player.points<=0)return;state.player.stats[k]++;state.player.points--;if(k==='force'){state.player.maxHp+=2;state.player.hp+=2}updateUI();tone(420,.05);}
  function equip(id){if(state.inCombat)return;const i=state.inventory.findIndex(w=>w.id===id);if(i<0)return;const old=state.player.weapon;state.player.weapon=state.inventory[i];state.inventory[i]=old;addLog(`${state.player.weapon.name} equipped.`,'good');updateUI();}
  function addLog(text,cls=''){state.logs.unshift({text,cls});state.logs=state.logs.slice(0,5);}
  function updateUI(){const p=state.player;$('#hero-name-display').textContent=p.name||'NAMELESS';$('#room-number').textContent=String(state.room).padStart(2,'0');$('#room-type').textContent=state.type==='boutique'?'SHOP':'EXPLORATION';$('#level').textContent=`LVL. ${p.level}`;$('#hp-text').textContent=`${Math.max(0,p.hp)} / ${p.maxHp}`;$('#hp-bar').style.width=`${Math.max(0,p.hp/p.maxHp*100)}%`;$('#xp-text').textContent=`${p.xp} / ${p.nextXp}`;$('#xp-bar').style.width=`${p.xp/p.nextXp*100}%`;$('#gold').textContent=p.gold;$('#points-left').textContent=`${p.points} PT`;$('#combat-lock').textContent=state.inCombat?'⚿ LOCKED':'';
    $('#stats').innerHTML=Object.entries(STAT).map(([k,s])=>`<div class="stat ${state.inCombat||!p.points?'locked':''}" data-stat="${k}" style="--stat-color:${s.color}"><span class="glyph">${s.glyph}</span><span><label>${s.label}</label><b>${p.stats[k]}</b></span><button>+</button></div>`).join('');document.querySelectorAll('[data-stat]').forEach(el=>el.onclick=()=>addStat(el.dataset.stat));
    const w=p.weapon;$('#equipped').style.setProperty('--weapon-color',STAT[w.stat].color);$('#equipped').innerHTML=`<span class="weapon-glyph">${w.glyph}</span><span class="weapon-info"><b>${w.name}</b><small>${STAT[w.stat].label} +${w.bonus}</small></span><b class="damage">${w.damage} DMG</b>`;$('#inventory').innerHTML=state.inventory.length?state.inventory.map(w=>`<button class="weapon" data-weapon="${w.id}" ${state.inCombat?'disabled':''} style="--weapon-color:${STAT[w.stat].color}"><b>${w.glyph} ${w.name}</b><small>${w.damage} DMG · ${STAT[w.stat].label}</small></button>`).join(''):'<span class="microcopy">Inventory empty</span>';document.querySelectorAll('[data-weapon]').forEach(el=>el.onclick=()=>equip(el.dataset.weapon));$('#log').innerHTML=state.logs.map(l=>`<p class="${l.cls}">${l.text}</p>`).join('');}
  function wallGlyph(x,y){const floor=(xx,yy)=>state.map[yy]?.[xx]==='.',l=floor(x-1,y),r=floor(x+1,y),u=floor(x,y-1),d=floor(x,y+1);if(!(l||r||u||d))return '';if((l||r)&&(u||d))return '+';return l||r?'│':'═';}
  function draw(){resize();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#050706';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.font=`${Math.max(12,Math.floor(tileH*.74))}px 'IBM Plex Mono'`;ctx.textAlign='center';ctx.textBaseline='middle';for(let y=0;y<H;y++)for(let x=0;x<W;x++){const tile=state.map[y]?.[x],px=ox+x*tileW+tileW/2,py=oy+y*tileH+tileH/2;if(tile==='#'){const glyph=wallGlyph(x,y);if(!glyph)continue;ctx.fillStyle='#666d68';ctx.globalAlpha=.82;ctx.fillText(glyph,px,py)}else if((x*17+y*31)%7===0){ctx.fillStyle='#373c39';ctx.globalAlpha=.7;ctx.fillText((x+y)%3?'·':'.',px,py)}}ctx.globalAlpha=1;if(state.exit){ctx.fillStyle=state.enemies.length?'#76543c':'#a8d46f';ctx.fillText(state.enemies.length?'▣':state.type==='boutique'?'$':'>',ox+state.exit.x*tileW+tileW/2,oy+state.exit.y*tileH+tileH/2)}for(const chest of state.chests){ctx.fillStyle='#f1bd55';ctx.shadowColor='#d9b463';ctx.shadowBlur=8;ctx.fillText('▣',ox+chest.x*tileW+tileW/2,oy+chest.y*tileH+tileH/2);ctx.shadowBlur=0}for(const potion of state.potions){ctx.fillStyle='#ed3f65';ctx.shadowColor='#ed3f65';ctx.shadowBlur=6;ctx.fillText('!',ox+potion.x*tileW+tileW/2,oy+potion.y*tileH+tileH/2);ctx.shadowBlur=0}for(const e of state.enemies){ctx.fillStyle=e.hp<e.maxHp*.4?'#ed3f65':e.glyph==='s'?'#b17fc9':'#56b864';ctx.fillText(e.glyph,ox+e.x*tileW+tileW/2,oy+e.y*tileH+tileH/2)}ctx.fillStyle='#f1f1e6';ctx.shadowColor='#d3ff8b';ctx.shadowBlur=7;ctx.fillText('@',ox+state.player.x*tileW+tileW/2,oy+state.player.y*tileH+tileH/2);ctx.shadowBlur=0;raf=requestAnimationFrame(draw);}
  function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;if(canvas.width!==r.width*d||canvas.height!==r.height*d){canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}tileW=Math.min(r.width/W,r.height/H);tileH=tileW;ox=(r.width-W*tileW)/2;oy=(r.height-H*tileH)/2;}
  function floatText(x,y,text,color){const el=document.createElement('span');el.className='float';el.textContent=text;el.style.color=color;el.style.left=`${ox+x*tileW}px`;el.style.top=`${oy+y*tileH}px`;$('#float-layer').append(el);setTimeout(()=>el.remove(),850);}
  function tone(freq,dur){if(audio)sound.beep(freq,dur,'square',.018,Math.max(25,freq*.72),.1)}
  function startGame(){sound.start();state=freshState();state.running=true;state.inventory=[makeWeapon(1),makeWeapon(1)];$('#start-screen').classList.remove('visible');$('#modal').classList.remove('visible');generateRoom();}
  const CONTROL_KEYS={azerty:{z:[0,-1],s:[0,1],q:[-1,0],d:[1,0]},arrows:{ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]},qwerty:{w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]}};
  const UNIVERSAL_KEYS={z:[0,-1],w:[0,-1],s:[0,1],q:[-1,0],a:[-1,0],d:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};
  function selectControls(mode){controlMode=CONTROL_KEYS[mode]?mode:'azerty';localStorage.setItem(STORAGE_CONTROLS,controlMode);const label={azerty:'ZQSD',arrows:'ARROWS',qwerty:'WASD'}[controlMode];$('#footer-controls').textContent=label;$('#start-control-hint').textContent=`${label} · SPACE TO WAIT`;}
  function detectControls(key){if(key.startsWith('Arrow'))selectControls('arrows');else if(key==='z'||key==='q')selectControls('azerty');else if(key==='w'||key==='a')selectControls('qwerty');}
  window.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(slotSession){if(e.key===' '){e.preventDefault();finalizeChest()}return}if($('#modal').classList.contains('visible')||!state.running)return;const normalized=e.key.length===1?e.key.toLowerCase():e.key,moveKey=UNIVERSAL_KEYS[normalized];if(moveKey){e.preventDefault();detectControls(normalized);move(...moveKey)}else if(e.key===' '){e.preventDefault();enemyTurn();updateCombat();updateUI()}else if(normalized==='r'&&confirm('Restart this chronicle?'))startGame()});
  $('#hero-name').value=localStorage.getItem(STORAGE_NAME)||'NAMELESS';$('#hero-name').addEventListener('input',e=>{const clean=e.target.value.replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,18).toUpperCase();e.target.value=clean;if(state?.player)state.player.name=clean||'NAMELESS';$('#hero-name-display').textContent=clean||'NAMELESS';localStorage.setItem(STORAGE_NAME,clean||'NAMELESS')});$('#hero-name').addEventListener('blur',e=>{if(!e.target.value.trim())e.target.value='NAMELESS';state.player.name=e.target.value.trim();$('#hero-name-display').textContent=state.player.name;localStorage.setItem(STORAGE_NAME,state.player.name)});$('#hero-name').addEventListener('keydown',e=>{if(e.key==='Enter'){$('#start-button').focus();startGame()}});
  $('#scores-button').onclick=showScores;$('#start-button').onclick=startGame;$('#sound-button').onclick=()=>{audio=!audio;$('#sound-button').textContent=`SOUND ${audio?'◼':'□'}`};$('#help-button').onclick=()=>{const m=$('#modal');m.innerHTML=`<div class="dialog guide-dialog"><span class="eyebrow">FIELD MANUAL // VERSION 1.0</span><h2>WANDERER'S GUIDE</h2><p class="guide-lead">There are no classes. Your attributes and current weapon define your build.</p><div class="guide-grid"><section><h3>ATTRIBUTES</h3><div class="guide-stat force"><b>◆ STRENGTH</b><span>Scales axes, warhammers and greatswords. Every point also grants +2 maximum HP.</span></div><div class="guide-stat agility"><b>» AGILITY</b><span>Scales daggers, rapiers and bows. Each point improves critical-hit and dodge chance.</span></div><div class="guide-stat magic"><b>✦ MAGIC</b><span>Scales staffs, orbs and scepters. Magic weapons also gain extra damage from Intellect.</span></div><div class="guide-stat intellect"><b>⌘ INTELLECT</b><span>Scales grimoires, catalysts and relic weapons. Also strengthens Magic weapon damage.</span></div></section><section><h3>COMBAT & PROGRESSION</h3><p>Walk into an enemy to attack. Every action advances one turn, then nearby enemies move or strike.</p><p>Defeating enemies grants XP and gold. Leveling restores all health, adds +5 maximum HP and awards 2 attribute points.</p><p class="warning">⚿ Equipment changes and point allocation are locked whenever an enemy is nearby.</p></section><section><h3>DUNGEON SYMBOLS</h3><div class="symbol-list"><span><b class="player-symbol">@</b> You</span><span><b class="enemy-symbol">r g s O</b> Enemies</span><span><b class="potion-symbol">!</b> Health potion</span><span><b class="chest-symbol">▣</b> Loot chest</span><span><b class="exit-symbol">&gt;</b> Open exit</span><span><b class="shop-symbol">$</b> Shop exit</span></div></section><section><h3>LOOT & SHOPS</h3><p>Health potions are rare monster drops and are consumed when stepped on.</p><p>Chests can contain gold, instant mini potions or permanent attribute relics. Press <kbd>SPACE</kbd> to stop the reward reels.</p><p>A weapon shop appears every 5 rooms. Compare weapon damage and its scaling attribute before buying.</p></section><section class="guide-wide"><h3>QUICK TIPS</h3><ul><li>Commit to one main weapon attribute, then add a complementary stat.</li><li>Agility supports any build through dodging; Strength adds survivability.</li><li>Clear every enemy before the exit unlocks.</li><li>Pick up healing only when needed—stepping on a potion consumes it even at full health.</li></ul></section></div><button class="primary" data-close>[ RETURN TO THE DUNGEON ]</button></div>`;m.classList.add('visible');$('[data-close]').onclick=()=>m.classList.remove('visible')};
  $('#sound-button').onclick=()=>{audio=!audio;sound.setEnabled(audio);$('#sound-button').textContent=`SOUND ${audio?'◼':'□'}`};
  selectControls(controlMode);
  state=freshState();updateUI();generateRoom();draw();
})();
